description: The project was developed for the IoT course in the Università del Salento (AY 2021/22)
domain: unisalento-idalab-iotcourse-2021-2022.github.io
baseurl: /wot-project-presentation-pierluigicosi
url:  https://unisalento-idalab-iotcourse-2021-2022.github.io
markdown: kramdown

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
